routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
	Route::get('/', 'AppController@index');

	Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin', 'namespace' => 'Admin'], function() {
		Route::get('/', [
			'uses' => 'AdminController@index',
			'as' => 'index',
		]);

		Route::resource('user', 'UserController');
		Route::resource('check-in', 'CheckInController');
		Route::resource('sector', 'SectorController');
		Route::resource('absence', 'AbsenceController');

		Route::group(['prefix' => 'ajax'], function() {
			Route::get('check-in/check-ins/{date}', 'CheckInController@getCheckedInForDate');
			Route::get('check-in/check-ins/{date}/stats', 'CheckInController@getStatsForDate');
			Route::get('check-in/get-checked-in', 'CheckInController@getCheckedIn');
			Route::get('check-in/{check_in}/edit', 'CheckInController@getEditCheckIn');
			Route::post('check-in/{check_in_id}/destroy', 'CheckInController@postDestroy');
			Route::post('check-in/{check_in_id}/stop', 'CheckInController@postStop');

			Route::get('user/{user_id}/check-ins', 'UserController@getCheckIns');
			Route::get('user/{user_id}/absence/vacations', 'UserController@getVacations');
			Route::get('user/{user_id}/absence/sick-leaves', 'UserController@getSickLeaves');

			Route::post('absence/{type}/{absence_id}/destroy', 'AbsenceController@postDestroy');
		});
	});

	Route::group(['prefix' => 'employee', 'namespace' => 'Frontend'], function() {
		Route::get('/', [
			'uses' => 'FrontendController@index',
			'as' => 'frontend.index',
		]);

		Route::post('check-in/make', [
			'uses' => 'CheckInController@postMake',
			'as' => 'frontend.check-in.make'
		]);
		Route::post('check-in/check-out', [
			'uses' => 'CheckInController@postCheckOut',
			'as' => 'frontend.check-in.check-out'
		]);
		Route::resource('check-in', 'CheckInController');
	});
});

Auth::routes();

Route::get('/logout', function() {
	\Auth::logout();
	return redirect('/');
});

app/Models/User/User.php
<?php

namespace App\Models\User;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use DB;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', "is_admin"
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];

    protected $appends = [
        'full_name'
    ];

    public function sectors() {
        return $this->belongsToMany('App\Models\Sector\Sector', 'user_sector')->withTimestamps();
    }

    public function checkIns() {
        return $this->hasMany('App\Models\CheckIn\CheckIn');
    }

    public function vacations() {
        return $this->hasMany('App\Models\Vacation\Vacation');
    }

    public function sickLeaves() {
        return $this->hasMany('App\Models\SickLeave\SickLeave');
    }

    public function scopeNotCheckedIn($query) {
        return $query->whereDoesntHave('checkIns', function($q) {
                $q->whereNull('check_out');
            })
            ->doesntHave('checkIns', 'or');
    }

    public function scopeWithTotalWorkingTime($query, $dateStart = null, $dateEnd = null) {
        $workingTime = $query->leftJoin('check_ins AS ci', 'ci.user_id', '=', 'users.id')
            ->select(DB::raw('SUM(TIME_TO_SEC(TIMEDIFF(ci.check_out, ci.check_in))) AS working_time'))
            ->groupBy('users.id')
            ->addSelect('users.*');
        /*if ($dateStart != null && $dateEnd != null) {
            $workingTime = $workingTime->whereHas('checkIns', function($query) {
                $query->whereDate('check_in', '>=', Carbon::createFromFormat('Y-m-d', $dateStart)->startOfDay()->toDateTimeString())
                    ->whereDate('check_in', '<=', Carbon::createFromFormat('Y-m-d', $dateEnd)->endOfDay()->toDateTimeString());
            });
        }*/
        return $workingTime;
    }

    public function scopeOnVacation($query) {
        return $query->whereHas('vacations', function($query) {
            $query->current();
        });
    }

    public function scopeOnSickLeave($query) {
        return $query->whereHas('sickLeaves', function($query) {
            $query->current();
        });
    }

    public function getCurrentVacationAttribute() {
        return $this->vacations->where('date_from', '<=', Carbon::today())
            ->where('date_to', '>=', Carbon::today())->first();
    }

    public function getCurrentSickLeaveAttribute() {
        return $this->sickLeaves->where('date_from', '<=', Carbon::today())
            ->where('date_to', '>=', Carbon::today())->first();
    }

    public function getAdminCheckAttribute() {
        return ($this->is_admin == 1) ? true : false;
    }

    public function getFullNameAttribute() {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getIsCheckedInAttribute() {
        $count = $this->checkIns()->whereNull('check_out')->count();
        return ($count > 0) ? true : false;
    }

    public function getTotalWorkingTimeHiAttribute() {
        $hours = floor($this->working_time / 3600);
        $mins = floor($this->working_time / 60 % 60);
        return sprintf('%02d:%02d', $hours, $mins);
    }

    public function setPasswordAttribute($value) {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Models/Vacation/Vacation.php
<?php

namespace App\Models\Vacation;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Vacation extends Model
{
	protected $fillable = [
		'date_from', 'date_to'
	];
	protected $dates = [
		'date_from', 'date_to'
	];

    public function user() {
		return $this->belongsTo('App\Models\User\User');
	}
	
	public function getDateFromDiffDaysAttribute() {
		return $this->date_from->diffInDays(Carbon::today());
	}

	public function scopeCurrent($query) {
		return $query->where('date_from', '<=', Carbon::today())
            ->where('date_to', '>=', Carbon::today());
	}

	public function setDateFromAttribute($value) {
		$this->attributes['date_from'] = Carbon::createFromFormat('d.m.Y.', $value)->startOfDay();
	}

	public function setDateToAttribute($value) {
		$this->attributes['date_to'] = Carbon::createFromFormat('d.m.Y.', $value)->startOfDay();
	}
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Repositories\UserRepository;

use App\Models\Sector\Sector;
use App\Models\User\User;

class UserController extends Controller
{
    public function __construct(UserRepository $users) {
        $this->users = $users;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $usersData = $this->users->getPaginated($request);
        $allUsers = User::all();
        $counts = [
            'total' => $this->users->totalCount(),
            'vacations' => $this->users->onVacationCount(),
            'sick_leaves' => $this->users->onSickLeaveCount()
        ];

        return view('admin.layouts.users.index', [
            'users' => $usersData['users'],
            'requestParams' => $usersData['request_params'],
            'searchTerm' => $usersData['search_term'],
            'counts' => $counts,
            'allUsers' => $allUsers
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sectors = Sector::pluck('name', 'id');
        return view('admin.layouts.users.create', [
            'sectors' => $sectors,
            'selected_sectors' => null
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::create($request->all());

        $sectors = [];
        if ($request->has('sectors')) $sectors = $request->input('sectors');
        $user->sectors()->sync($sectors);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::withTotalWorkingTime()->with('sectors', 'checkIns')
            ->where('users.id', $id)->first();

        return view('admin.layouts.users.show', [
            'user' => $user
        ]);
    }

    public function getCheckIns(Request $request, $id) {
        if ($request->ajax()) {
            $user = User::where('id', $id)->first();
            $checkIns = $user->checkIns()->orderBy('check_in', 'DESC')->paginate(5);
            return response()->json($checkIns);
        }
    }

    public function getVacations(Request $request, $id) {
        if ($request->ajax()) {
            $user = User::where('id', $id)->first();
            $vacations = $user->vacations()->orderBy('date_from', 'DESC')->paginate(5);
            return response()->json($vacations);
        }
    }

    public function getSickLeaves(Request $request, $id) {
        if ($request->ajax()) {
            $user = User::where('id', $id)->first();
            $sickLeaves = $user->sickLeaves()->orderBy('date_from', 'DESC')->paginate(5);
            return response()->json($sickLeaves);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::where('id', $id)->first();
        $sectors = Sector::pluck('name', 'id');
        $selectedSectors = $user->sectors->pluck('id')->toArray();
        return view('admin.layouts.users.edit', [
            'sectors' => $sectors,
            'selected_sectors' => $selectedSectors,
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::where('id', $id)->first();
        $requestData = $request->all();
        if ($requestData['password'] == '' || $requestData['password'] == null) {
            $requestData = $request->except(['password']);
        }
        $user->update($requestData);

        $sectors = [];
        if ($request->has('sectors')) $sectors = $request->input('sectors');
        $user->sectors()->sync($sectors);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::where('id', $id)->first();
        $user->delete();

        return redirect()->back();
    }
}

resources/views/admin/layouts/users/create.blade.php
@extends('admin.layouts.master')

@section('main')

<div class="container">
	<div class="row">
		<div class="col-md-8 col-xs-12">
			<h1 class="_title-main _v-center-items">
				Novi zaposlenik
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-9">
			{!! Form::open(['route' => ['admin.user.store'], 'class' => 'form-horizontal']) !!}
				<div class="well">
					@include('admin.layouts.users.includes.partials.form')
				</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

@endsection

@section('js-after')

<script>
	$(document).ready(function() {
		
	});
</script>

@endsection

resources/views/admin/layouts/users/edit.blade.php
@extends('admin.layouts.master')

@section('main')

<div class="container">
	<div class="row">
		<div class="col-md-8 col-xs-12">
			<h1 class="_title-main _v-center-items">
				Uredi podatke o zaposleniku
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-9">
			{!! Form::model($user, ['method' => 'PUT', 'route' => ['admin.user.update', $user->id], 'class' => 'form-horizontal']) !!}
				<div class="well">
					@include('admin.layouts.users.includes.partials.form')
				</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

@endsection

@section('js-after')

<script>
	$(document).ready(function() {

	});
</script>

@endsection

resources/views/admin/layouts/users/index.blade.php
@extends('admin.layouts.master')

@section('main')

<div class="container">
	<div class="row">
		<div class="col-md-8 col-xs-12">
			<h1 class="_title-main _v-center-items">
				Pregled zaposlenika
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8">
			<div id="curr-chk-ins__holder" class="panel panel-default">
				<div class="panel-heading _no-padding">
					<div class="row _v-center-items">
			            <div class="col-sm-9 col-xs-12">
							<ul class="nav nav-tabs nav-justified">
								<li role="presentation" class="{{ (!isSetGetParam('absence')) ? 'active' : '' }}">
									<a href="{{ route('admin.user.index') }}">Svi <span class="label label-primary _marginLeft6">{{ $counts['total'] }}</span></a>
								</li>
								<li role="presentation" class="{{ isActiveGetParam('absence', 'vacations') }}">
									<a href="{{ route('admin.user.index', ['absence' => 'vacations']) }}">Na godišnjem <span class="label label-primary _marginLeft6">{{ $counts['vacations'] }}</span></a>
								</li>
								<li role="presentation" class="{{ isActiveGetParam('absence', 'sick-leaves') }}">
									<a href="{{ route('admin.user.index', ['absence' => 'sick-leaves']) }}">Na bolovanju <span class="label label-primary _marginLeft6">{{ $counts['sick_leaves'] }}</span></a>
								</li>
							</ul>
						</div>
						<div class="col-sm-3 col-xs-12 clearfix" style="padding-right: 30px;">
							<div class="btn-group pull-right">
								<div class="btn-group">
									<a href="#" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown">
										<span class="fa fa-sort-amount-desc"></span>
										<span class="caret"></span>
									</a>
									<ul class="dropdown-menu pull-right">
										<li class="{{ (!isSetGetParam('order_by')) ? 'active' : isActiveGetParam('order_by', 'last_name_asc') }}">
											<a href="{{ route('admin.user.index', arraySet($requestParams, 'order_by', 'last_name_asc')) }}">
												<span class="fa fa-sort-alpha-asc"></span>Prezime A-Ž
											</a>
										</li>
										<li class="{{ isActiveGetParam('order_by', 'last_name_desc') }}">
											<a href="{{ route('admin.user.index', arraySet($requestParams, 'order_by', 'last_name_desc')) }}">
												<span class="fa fa-sort-alpha-desc"></span>Prezime Ž-A
											</a>
										</li>
										@if (isset($requestParams['absence']))
										@else
										<li class="{{ isActiveGetParam('order_by', 'created_at_desc') }}">
											<a href="{{ route('admin.user.index', arraySet($requestParams, 'order_by', 'created_at_desc')) }}">
												<span class="fa fa-calendar-plus-o"></span>Najnovije kreirani
											</a>
										</li>
										<li class="{{ isActiveGetParam('order_by', 'created_at_asc') }}">
											<a href="{{ route('admin.user.index', arraySet($requestParams, 'order_by', 'created_at_asc')) }}">
												<span class="fa fa-calendar"></span>Najstarije kreirani
											</a>
										</li>
										<li class="{{ isActiveGetParam('order_by', 'working_time_asc') }}">
											<a href="{{ route('admin.user.index', arraySet($requestParams, 'order_by', 'working_time_asc')) }}">
												<span class="fa fa-hourglass-start"></span>Najmanje vrijeme rada
											</a>
										</li>
										<li class="{{ isActiveGetParam('order_by', 'working_time_desc') }}">
											<a href="{{ route('admin.user.index', arraySet($requestParams, 'order_by', 'working_time_desc')) }}">
												<span class="fa fa-hourglass-end"></span>Najveće vrijeme rada
											</a>
										</li>
										@endif
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			    <div class="panel-body">
			    	<div class="row _marginBtm15">
				    	<div class="col-xs-12">
							{!! Form::open(['method' => 'GET', 'url' => Request::url()]) !!}
							<div class="form-group" style="margin: 0;">
								<div class="input-group">
									<input type="text" class="form-control input-sm" placeholder="pretraži zaposlenike" name="search" value="{{ $searchTerm or '' }}">
									<span class="input-group-btn">
										<button type="submit" class="btn btn-sm btn-default" type="button">
											<i class="fa _fa-reset fa-search"></i>
										</button>
									</span>
								</div>
							</div>
							{!! Form::close() !!}
						</div>
					</div>
			    	<div class="row">
				    	<div class="col-xs-12">
					        <div class="table-responsive">
								<table class="table table-hover table-hover">
									<thead>
										<tr>
											<th>ID</th>
											<th>Zaposlenik</th>
											<th>Email</th>
											@if (isset($requestParams['absence']))
											<th>Od</th>
											<th>Do</th>
											@else
											<th>Sektori</th>
											<th>Vrijeme rada</th>
											@endif
											<th></th>
										</tr>
									</thead>
									<tbody>
										@foreach($users as $user)
										<tr>
											<td>{{ $user->id }}</td>
											<td>{{ $user->full_name }}</td>
											<td>{{ $user->email }}</td>
											@if (isset($requestParams['absence']))
												@if ($requestParams['absence'] == 'vacations')
												<td>{{ $user->current_vacation->date_from->format('d.m.Y.') }} <small>({{$user->current_vacation->date_from_diff_days}} dana)</small></td>
												<td>{{ $user->current_vacation->date_to->format('d.m.Y.') }}</td>
												@elseif ($requestParams['absence'] == 'sick-leaves')
												<td>{{ $user->current_sick_leave->date_from->format('d.m.Y.') }} <small>({{$user->current_sick_leave->date_from_diff_days}} dana)</small></td>
												<td>{{ $user->current_sick_leave->date_to->format('d.m.Y.') }}</td>
												@endif
											@else
											<td>
												@foreach($user->sectors as $sector)
													<span class="label label-default">{{ $sector->abbrevation }}</span>
												@endforeach
											</td>
											<td>{{ $user->total_working_time_hi }}</td>
											@endif
											<td class="_nowrap _text-right">
												@if (isset($requestParams['absence']))
													
												@else
												<a href="{{route('admin.user.edit', $user->id)}}" class="btn btn-primary btn-xs">Uredi</button>
												<a href="{{route('admin.user.show', $user->id)}}" class="_marginLeft6 btn btn-info btn-xs"><span class="fa fa-user _fa-reset"></span></a>
												<div style="display: inline-block;">
													{!! Form::open(['route' => ['admin.user.destroy', $user->id], 'method' => 'DELETE']) !!}
														<a class="btn btn-danger btn-xs" onclick="confirmToDelete(this)" style="{{ ($user->id != Auth::user()->id) ? 'display: inline-block' : 'visibility: hidden' }}">
															<span class="fa fa-remove _fa-reset"></span>
														</a>
													{!! Form::close() !!}
												</div>
												@endif
											</td>
										</tr>
										@endforeach
									</tbody>
								</table>
							</div>
							<div class="pull-right clearfix _rendered-pagin">
								{!! $users->appends($requestParams)->render() !!}
							</div>
						</div>
					</div>
			    </div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="row">
				<div class="col-xs-12">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title clearfix">
			                    Odsutnosti
			                </h3>
						</div>
						<div class="panel-body">
							{!! Form::open(['route' => ['admin.absence.store']]) !!}
								<fieldset>
									<div class="form-group">
					                    <label class="control-label">Vrsta</label>
					                    	<div class="row">
						                    	<div class="col-xs-6">
													<div class="radio">
														<label>
															<input type="radio" name="absence_type" value="sick_leave" checked>
															Bolovanje
														</label>
													</div>
												</div>
												<div class="col-xs-6">
													<div class="radio">
														<label>
															<input type="radio" name="absence_type" value="vacation">
															Godišnji
														</label>
													</div>
												</div>
											</div>
					                    </div>
									<div class="form-group">
					                    <label class="control-label">Od (datum)</label>
										<div class='input-group' id="absence-date-from">
											<input type="text" class="form-control _date" placeholder="od" name="date_from">
						                    <span class="input-group-addon">
						                        <span class="glyphicon glyphicon-calendar"></span>
						                    </span>
						                </div>
									</div>
									<div class="form-group">
					                    <label class="control-label">Do (datum)</label>
										<div class='input-group' id="absence-date-to">
											<input type="text" class="form-control _date" placeholder="do" name="date_to">
						                    <span class="input-group-addon">
						                        <span class="glyphicon glyphicon-calendar"></span>
						                    </span>
						                </div>
									</div>
									<div class="form-group">
										<label class="control-label">Zaposlenici</label>
										<select class="form-control _select" name="user">
											@foreach($allUsers as $user)
											<option value="{{ $user->id }}">{{ $user->full_name }}</option>
											@endforeach
					                    </select>
				                    </div>
									<div class="clearfix">
					                    <div class="pull-right">
											<button type="submit" class="btn btn-primary">Spremi</button>
					                    </div>
					                </div>
								</fieldset>
							{!! Form::close() !!}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@section('js-after')

<script>
	$(document).ready(function() {
		$('#absence-date-to input').datetimepicker({
			format: 'DD.MM.YYYY.'
		});
		$('#absence-date-from input').datetimepicker({
			format: 'DD.MM.YYYY.'
		});
		$('._select').select2();
	});
</script>

@endsection

resources/views/admin/layouts/users/show.blade.php
@extends('admin.layouts.master')

@section('main')

<div class="container _user-show">
	<h1>
		{{ $user->full_name }}
		<span class="label label-info _marginLeft6" style="font-size: 12px; vertical-align: middle">
			@if($user->is_admin)
			Administrator
			@else
			Zaposlenik
			@endif
		</span>
	</h1>
	<div class="row">
		<div class="col-sm-7">
			<div class="well">
				<h3 class="clearfix">
					Općeniti podaci
					<a href="{{route('admin.user.edit', $user->id)}}" class="btn btn-default btn-xs pull-right">Uredi</a>
				</h3>
				<div class="row">
					<div class="col-sm-6">
						<dl>
							<dt>Email adresa</dt>
							<dd>{{ $user->email }}</dd>
							<dt>Sektori</dt>
							<dd>
								@foreach($user->sectors as $sector)
								<span class="label label-default">{{ $sector->abbrevation }}</span>
								@endforeach
							</dd>
						</dl>
					</div>
					<div class="col-sm-6">
						<dl>
							<dt>Kreiran</dt>
							<dd>{{ $user->created_at->format('d.m.Y') }}</dd>
							<dt>Ažuriran</dt>
							<dd>{{ $user->updated_at->format('d.m.Y') }}</dd>
						</dl>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-offset-2 col-md-3 col-sm-offset-0 col-sm-5">
			<div class="well">
				<div class="row">
					<div class="col-xs-12 _counter-holder">
						<span class="_counter-title">Sati rada</span>
						<span class="_counter-num">{{ $user->total_working_time_hi or '0'}}</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-7">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="row _v-center-items">
			            <div class="col-sm-6 col-xs-12">
			                <h3 class="panel-title clearfix">
			                    Prijave
			                    <span class="label label-primary _marginLeft6" id="user-check-ins-total"></span>
			                </h3>
			            </div>
			            <div class="col-sm-6 col-xs-12">
			                <div class="form-inline clearfix pull-right">
			                    <div class="form-group" id="user-check-ins-pag" data-user="{{ $user->id }}">
			                        <div class="btn-group" role="group">
			                            <button type="button" class="_pag__first btn btn-sm btn-default"><i class="fa fa-angle-double-left _fa-reset _fa-bigger"></i></button>
			                            <button type="button" class="_pag__prev btn btn-sm btn-default"><i class="fa fa-angle-left _fa-reset _fa-bigger"></i></button>
			                            <button type="button" class="_pag__next btn btn-sm btn-default"><i class="fa fa-angle-right _fa-reset _fa-bigger"></i></button>
			                            <button type="button" class="_pag__last btn btn-sm btn-default"><i class="fa fa-angle-double-right _fa-reset _fa-bigger"></i></button>
			                        </div>
			                    </div>
			                </div>
			            </div>
			        </div>
				</div>
				<div class="panel-body">
					@include('admin.layouts.users.includes.handlebars.check-ins')
					<div id="user-check-ins-holder"></div>
				</div>
			</div>
		</div>
		<div class="col-md-5">
			<div class="panel panel-default">
				<div class="panel-heading _no-padding">
					<div class="row _v-center-items">
						<div class="col-sm-8">
							<ul class="nav nav-tabs nav-justified">
								<li role="presentation" class="active">
									<a href="" data-toggle="tab" onclick="userAbsenceTypeChanged('sick_leaves')">Bolovanja</a>
								</li>
								<li role="presentation" class="">
									<a href="" data-toggle="tab" onclick="userAbsenceTypeChanged('vacations')">Godišnji</a>
								</li>
							</ul>
						</div>
						<div class="col-sm-4">
							<div class="form-inline clearfix pull-right" style="padding-right: 15px;">
			                    <div class="form-group" id="user-absences-pag" data-absence-type="sick_leaves" data-user="{{ $user->id }}">
			                        <div class="btn-group" role="group">
			                            <button type="button" class="_pag__first btn btn-sm btn-default"><i class="fa fa-angle-double-left _fa-reset _fa-bigger"></i></button>
			                            <button type="button" class="_pag__prev btn btn-sm btn-default"><i class="fa fa-angle-left _fa-reset _fa-bigger"></i></button>
			                            <button type="button" class="_pag__next btn btn-sm btn-default"><i class="fa fa-angle-right _fa-reset _fa-bigger"></i></button>
			                            <button type="button" class="_pag__last btn btn-sm btn-default"><i class="fa fa-angle-double-right _fa-reset _fa-bigger"></i></button>
			                        </div>
			                    </div>
			                </div>
						</div>
					</div>
				</div>
				<div class="panel-body">
					@include('admin.layouts.users.includes.handlebars.vacations')
					<div id="user-absences-holder"></div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@section('js-after')

<script>
	$(document).ready(function() {
		paginateAjaxForTemplate(null, null, 'user-check-ins-pag', 'user-check-ins-hbt', 'user-check-ins-holder');
		paginateAjaxForTemplate(null, null, 'user-absences-pag', 'user-vacations-hbt', 'user-absences-holder');
	});
</script>

@endsection