routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
	Route::get('/', 'AppController@index');

	Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin', 'namespace' => 'Admin'], function() {
		Route::get('/', [
			'uses' => 'AdminController@index',
			'as' => 'index',
		]);

		Route::resource('user', 'UserController');
		Route::resource('check-in', 'CheckInController');
		Route::resource('sector', 'SectorController');
		Route::resource('absence', 'AbsenceController');

		Route::group(['prefix' => 'ajax'], function() {
			Route::get('check-in/check-ins/{date}', 'CheckInController@getCheckedInForDate');
			Route::get('check-in/check-ins/{date}/stats', 'CheckInController@getStatsForDate');
			Route::get('check-in/get-checked-in', 'CheckInController@getCheckedIn');
			Route::get('check-in/{check_in}/edit', 'CheckInController@getEditCheckIn');
			Route::post('check-in/{check_in_id}/destroy', 'CheckInController@postDestroy');
			Route::post('check-in/{check_in_id}/stop', 'CheckInController@postStop');

			Route::get('user/{user_id}/check-ins', 'UserController@getCheckIns');
			Route::get('user/{user_id}/absence/vacations', 'UserController@getVacations');
			Route::get('user/{user_id}/absence/sick-leaves', 'UserController@getSickLeaves');

			Route::post('absence/{type}/{absence_id}/destroy', 'AbsenceController@postDestroy');
		});
	});

	Route::group(['prefix' => 'employee', 'namespace' => 'Frontend'], function() {
		Route::get('/', [
			'uses' => 'FrontendController@index',
			'as' => 'frontend.index',
		]);

		Route::post('check-in/make', [
			'uses' => 'CheckInController@postMake',
			'as' => 'frontend.check-in.make'
		]);
		Route::post('check-in/check-out', [
			'uses' => 'CheckInController@postCheckOut',
			'as' => 'frontend.check-in.check-out'
		]);
		Route::resource('check-in', 'CheckInController');
	});
});

Auth::routes();

Route::get('/logout', function() {
	\Auth::logout();
	return redirect('/');
});

resources/views/home.blade.php
<!DOCTYPE html>
<html lang="en" class="_v-center-items" style="height: 100%;">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'Laravel') }}</title>
        {!! Html::style('https://fonts.googleapis.com/css?family=Lato:400,300,700,900&subset=latin,latin-ext') !!}
        <link href="/css/admin.css" rel="stylesheet">
    </head>
    <body style="width: 100%;">
        <div id="app">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6 text-center">
                        <a href="{{ route('frontend.index') }}" class="btn btn-lg btn-info btn-block" style="padding: 40px 15px; margin: 10px 0;">Zaposlenici</a>
                    </div>
                    <div class="col-sm-6 text-center">
                    <a href="{{ route('admin.index') }}" class="btn btn-lg btn-primary btn-block" style="padding: 40px 15px; margin: 10px 0;">Administracija</a>
                    </div>
                </div>
                <div class="row" style="margin-top: 30px;">
                    <div class="col-sm-offset-3 col-sm-6 col-xs-12">
                        {{ Form::open(['method' => 'POST', 'action' => 'Auth\LoginController@logout'])}}
                        <button type="submit" class="btn btn-default btn-block" style="padding: 20px 15px;">Odjava</button>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>