routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
	Route::get('/', 'AppController@index');

	Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin', 'namespace' => 'Admin'], function() {
		Route::get('/', [
			'uses' => 'AdminController@index',
			'as' => 'index',
		]);

		Route::resource('user', 'UserController');
		Route::resource('check-in', 'CheckInController');
		Route::resource('sector', 'SectorController');
		Route::resource('absence', 'AbsenceController');

		Route::group(['prefix' => 'ajax'], function() {
			Route::get('check-in/check-ins/{date}', 'CheckInController@getCheckedInForDate');
			Route::get('check-in/check-ins/{date}/stats', 'CheckInController@getStatsForDate');
			Route::get('check-in/get-checked-in', 'CheckInController@getCheckedIn');
			Route::get('check-in/{check_in}/edit', 'CheckInController@getEditCheckIn');
			Route::post('check-in/{check_in_id}/destroy', 'CheckInController@postDestroy');
			Route::post('check-in/{check_in_id}/stop', 'CheckInController@postStop');

			Route::get('user/{user_id}/check-ins', 'UserController@getCheckIns');
			Route::get('user/{user_id}/absence/vacations', 'UserController@getVacations');
			Route::get('user/{user_id}/absence/sick-leaves', 'UserController@getSickLeaves');

			Route::post('absence/{type}/{absence_id}/destroy', 'AbsenceController@postDestroy');
		});
	});

	Route::group(['prefix' => 'employee', 'namespace' => 'Frontend'], function() {
		Route::get('/', [
			'uses' => 'FrontendController@index',
			'as' => 'frontend.index',
		]);

		Route::post('check-in/make', [
			'uses' => 'CheckInController@postMake',
			'as' => 'frontend.check-in.make'
		]);
		Route::post('check-in/check-out', [
			'uses' => 'CheckInController@postCheckOut',
			'as' => 'frontend.check-in.check-out'
		]);
		Route::resource('check-in', 'CheckInController');
	});
});

Auth::routes();

Route::get('/logout', function() {
	\Auth::logout();
	return redirect('/');
});

app/Models/Sector/Sector.php
<?php

namespace App\Models\Sector;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sector extends Model
{
	use SoftDeletes;

	protected $fillable = [
		'name', 'abbrevation'
	];

    public function users() {
		return $this->belongsToMany('App\Models\User\User', 'user_sector')->withTimestamps();
	}
}

app/Http/Controllers/Admin/SectorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Repositories\SectorRepository;
use App\Repositories\UserRepository;


use App\Models\Sector\Sector;
use App\Models\User\User;

class SectorController extends Controller
{
    public function __construct(SectorRepository $sectors, UserRepository $users) {
        $this->sectors = $sectors;
        $this->users = $users;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $sectorsData = $this->sectors->getPaginated($request);
        $users = $this->users->generateUsersForList(User::all());
        $counts = [
            'total' => $this->sectors->totalCount()
        ];

        return view('admin.layouts.sectors.index', [
            'sectors' => $sectorsData['sectors'],
            'requestParams' => $sectorsData['request_params'],
            'searchTerm' => $sectorsData['search_term'],
            'users' => $users,
            'counts' => $counts,
            'selected_users' => null
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$sectors = Sector::all();
        return view('admin.layouts.sectors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $sector = Sector::create($request->all());

        $users = [];
        if ($request->has('users')) $users = $request->input('users');
        $sector->users()->sync($users);
        
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sector = Sector::where('id', $id)->first();
        $users = $this->users->generateUsersForList(User::all());
        $selectedUsers = $sector->users->pluck('id')->toArray();
        return view('admin.layouts.sectors.edit', [
            'sector' => $sector,
            'users' => $users,
            'selected_users' => $selectedUsers
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $sector = Sector::where('id', $id)->first();
        $sector->update($request->all());

        $users = [];
        if ($request->has('users')) $users = $request->input('users');
        $sector->users()->sync($users);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sector = Sector::where('id', $id)->first();
        $sector->delete();

        return redirect()->back();
    }
}

resources/views/admin/layouts/sectors/create.blade.php
@extends('admin.layouts.master')

@section('main')

<div class="container">
	<div class="row">
		<div class="col-md-8 col-xs-12">
			<h1 class="_title-main _v-center-items">
				Novi sektor
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-9">
			
		</div>
	</div>
</div>

@endsection

@section('js-after')

<script>
	$(document).ready(function() {

	});
</script>

@endsection

resources/views/admin/layouts/sectors/edit.blade.php
@extends('admin.layouts.master')

@section('main')

<div class="container">
	<div class="row">
		<div class="col-md-8 col-xs-12">
			<h1 class="_title-main _v-center-items">
				Uredi podatke o sektoru
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-7">
			{!! Form::model($sector, ['method' => 'PUT', 'route' => ['admin.sector.update', $sector->id]]) !!}
				<div class="well">
					@include('admin.layouts.sectors.includes.partials.form')
				</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

@endsection

@section('js-after')

<script>
	$(document).ready(function() {

	});
</script>

@endsection

resources/views/admin/layouts/sectors/index.blade.php
@extends('admin.layouts.master')

@section('main')

<div class="container">
	<div class="row">
		<div class="col-md-8 col-xs-12">
			<h1 class="_title-main">
				Pregled sektora
				<span class="badge _marginLeft6">ukupno: <strong>{{ $counts['total'] }}</strong></span>
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8">
			<div id="curr-chk-ins__holder" class="panel panel-default">
				<div class="panel-heading">
					<div class="row _v-center-items">
						<div class="col-sm-6 col-xs-8">
							{!! Form::open(['method' => 'GET', 'url' => Request::url()]) !!}
							<div class="form-group" style="margin: 0;">
								<div class="input-group">
									<input type="text" class="form-control input-sm" placeholder="pretraži sektore" name="search" value="{{ $searchTerm or '' }}">
									<span class="input-group-btn">
										<button type="submit" class="btn btn-sm btn-default" type="button">
											<i class="fa _fa-reset fa-search"></i>
										</button>
									</span>
								</div>
							</div>
							{!! Form::close() !!}
						</div>
						<div class="col-sm-6 col-xs-4 clearfix">
							<div class="btn-group pull-right">
								<div class="btn-group">
									<a href="#" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown">
										<span class="fa fa-sort-amount-desc"></span>
										<span class="caret"></span>
									</a>
									<ul class="dropdown-menu pull-right">
										<li class="{{ (!isSetGetParam('order_by')) ? 'active' : isActiveGetParam('order_by', 'name_asc') }}">
											<a href="{{ route('admin.sector.index', arraySet($requestParams, 'order_by', 'name_asc')) }}">
												<span class="fa fa-sort-alpha-asc"></span>Naziv A-Ž
											</a>
										</li>
										<li class="{{ isActiveGetParam('order_by', 'name_desc') }}">
											<a href="{{ route('admin.sector.index', arraySet($requestParams, 'order_by', 'name_desc')) }}">
												<span class="fa fa-sort-alpha-desc"></span>Naziv Ž-A
											</a>
										</li>
										<li class="{{ isActiveGetParam('order_by', 'emp_count_asc') }}">
											<a href="{{ route('admin.sector.index', arraySet($requestParams, 'order_by', 'emp_count_asc')) }}">
												<span class="fa fa-sort-alpha-desc"></span>Najmanja zastupljenost
											</a>
										</li>
										<li class="{{ isActiveGetParam('order_by', 'emp_count_desc') }}">
											<a href="{{ route('admin.sector.index', arraySet($requestParams, 'order_by', 'emp_count_desc')) }}">
												<span class="fa fa-sort-alpha-desc"></span>Najveća zastupljenost
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			    <div class="panel-body">
			        <div class="table-responsive">
						<table class="table table-hover table-hover">
							<thead>
								<tr>
									<th>ID</th>
									<th>Naziv</th>
									<th>Kratica</th>
									<th>#</th>
									<th>Kreiran</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								@foreach($sectors as $sector)
								<tr>
									<td>{{ $sector->id }}</td>
									<td>{{ $sector->name }}</td>
									<td>{{ $sector->abbrevation }}</td>
									<td>
										<span class="label label-primary">{{ $sector->users_count }}</span>
									</td>
									<td>{{ $sector->created_at->format('d.m.Y.') }}</td>
									<td class="_nowrap _text-right">
										<a href="{{ route('admin.sector.edit', $sector->id) }}" class="btn btn-primary btn-xs">
											Uredi
										</a>
										<div style="display: inline-block;">
											{!! Form::open(['route' => ['admin.sector.destroy', $sector->id], 'method' => 'DELETE']) !!}
												<a class="btn btn-danger btn-xs _delete-conf" onclick="confirmToDelete(this)"><span class="fa fa-remove _fa-reset"></span></a>
											{!! Form::close() !!}
										</div>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
					<div class="pull-right clearfix _rendered-pagin">
						{!! $sectors->appends($requestParams)->render() !!}
					</div>
			    </div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="row">
				<div class="col-xs-12">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title clearfix">
			                    Novi sektor
			                </h3>
						</div>
						<div class="panel-body">
							{!! Form::open(['route' => ['admin.sector.store']]) !!}
								@include('admin.layouts.sectors.includes.partials.form')
							{!! Form::close() !!}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@section('js-after')
<script>

</script>
    @endsection