routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
	Route::get('/', 'AppController@index');

	Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin', 'namespace' => 'Admin'], function() {
		Route::get('/', [
			'uses' => 'AdminController@index',
			'as' => 'index',
		]);

		Route::resource('user', 'UserController');
		Route::resource('check-in', 'CheckInController');
		Route::resource('sector', 'SectorController');
		Route::resource('absence', 'AbsenceController');

		Route::group(['prefix' => 'ajax'], function() {
			Route::get('check-in/check-ins/{date}', 'CheckInController@getCheckedInForDate');
			Route::get('check-in/check-ins/{date}/stats', 'CheckInController@getStatsForDate');
			Route::get('check-in/get-checked-in', 'CheckInController@getCheckedIn');
			Route::get('check-in/{check_in}/edit', 'CheckInController@getEditCheckIn');
			Route::post('check-in/{check_in_id}/destroy', 'CheckInController@postDestroy');
			Route::post('check-in/{check_in_id}/stop', 'CheckInController@postStop');

			Route::get('user/{user_id}/check-ins', 'UserController@getCheckIns');
			Route::get('user/{user_id}/absence/vacations', 'UserController@getVacations');
			Route::get('user/{user_id}/absence/sick-leaves', 'UserController@getSickLeaves');

			Route::post('absence/{type}/{absence_id}/destroy', 'AbsenceController@postDestroy');
		});
	});

	Route::group(['prefix' => 'employee', 'namespace' => 'Frontend'], function() {
		Route::get('/', [
			'uses' => 'FrontendController@index',
			'as' => 'frontend.index',
		]);

		Route::post('check-in/make', [
			'uses' => 'CheckInController@postMake',
			'as' => 'frontend.check-in.make'
		]);
		Route::post('check-in/check-out', [
			'uses' => 'CheckInController@postCheckOut',
			'as' => 'frontend.check-in.check-out'
		]);
		Route::resource('check-in', 'CheckInController');
	});
});

Auth::routes();

Route::get('/logout', function() {
	\Auth::logout();
	return redirect('/');
});

resources/views/admin/includes/modal-date-picker.blade.php
<div class="modal fade" id="modal-checkins-date-picker" tabindex="-1" role="dialog" data-backdrop="static">
	<div class="modal-dialog" id="modal-edit-checkin-holder">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">Odabir datuma evidencije</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
			        <div id="checkins-date-picker"></div>
			    </div>
			</div>
			<div class="modal-footer clearfix">
				<button href="#" class="btn btn-default" data-dismiss="modal">Odustani</button>
		    </div>
		</div>
	</div>
</div>

resources/views/admin/includes/modal-edit-checkin.blade.php
<div class="modal fade" id="modal-edit-checkin" tabindex="-1" role="dialog" data-backdrop="static">
	@include('admin.includes.handlebars.modal-edit-checkin')
	<div class="modal-dialog" id="modal-edit-checkin-holder">
		
	</div>
</div>

resources/views/admin/includes/nav.blade.php
<nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/admin">EDNAP</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li class="{{ active('admin.index') }}"><a href="{{ route('admin.index') }}">Evidencija</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Zaposlenici <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('admin.user.index') }}">Pregled</a></li>
                        <li><a href="{{ route('admin.user.create') }}">Dodaj novog</a></li>
                    </ul>
                </li>
                <li class="{{ active('admin.sector.index') }}"><a href="{{ route('admin.sector.index') }}">Sektori</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administrator <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="/logout">Odjava</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>